# Generated by Django 5.0.6 on 2024-07-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_assigned_to_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='assigned_to',
        ),
    ]
